### ISSUE TITLE
Message input background is white

### ISSUE THREAD

**Issue by Hulth** [cicerakes/DarkNight-FBMessenger#1]
- **Browser:** Google Chrome Version 75.0.3770.142 (Official) (64 bit)
- **Occurs on messenger.com or Facebook?** messenger.com

**Describe the problem**
The background of the "write message"-field is white.

**Screenshots:**
![dark messenger](https://user-images.githubusercontent.com/272555/61595109-6025bf80-abf3-11e9-9ab1-c6e3fff27553.png)

**Comment by AdrianCGonzalez** [comment]
@Hulth Add this to your style to fix

`._kmc._7kpg ._1p1t {
    color: rgba(255, 255, 255, .50);
    -webkit-text-fill-color: rgba(255, 255, 255, .50);
}
._5irm._7mkm {
    background-color: #1e1e1e !important;
}
`
