### ISSUE TITLE
White background on chat switch

### ISSUE THREAD

**Issue by ghost** [cicerakes/DarkNight-FBMessenger#12]
- **Browser:** any
- **Occurs on messenger.com or Facebook?** messenger.com

**Describe the problem**
On switching between chats the background before sliding down is white.

**Proposed solution:**
Add background-color: #1e1e1e; to the body element.

**Comment by NellyWhads** [comment]
Can we mark this issue as resolved? Can't seem to reproduce it, and it seems it was explicitly fixed. Just wondering 😇

**Comment by cicerakes** [comment]
I am also unable to reproduce it at the moment. It may have resolved on its own due to changes/updates made by Facebook. 
I will be closing this for now, but it can be re-opened if more details on reproducing it are provided.

**Comment by ghost** [comment]
I can't reproduce it either. Seems it has been fixed by changes from fb.
