### ISSUE TITLE
Enhancement: Include Auto-Dark mode

### ISSUE THREAD

**Issue by RolandUdv** [cicerakes/DarkNight-FBMessenger#16]
I would like to recommend adding an option for scheduling the Dark theme only when Dark Mode is used on a device.

This is supported on Chrome and Edge for now, didn't have much luck with other Chromium engines including Opera.

```
@media (prefers-color-scheme: dark){
   .body {
   }
}
```

I've edited the theme via Stylish and it seems to work well.

**Comment by cicerakes** [comment]
This is something that should soon be added to Stylus itself, so I won't be implementing it for just this style. 
More details here: https://github.com/openstyles/stylus/pull/736
