### ISSUE TITLE
Reply bubble not shaded correctly

### ISSUE THREAD

**Issue by indigo5ive** [cicerakes/DarkNight-FBMessenger#18]
- **Browser:** Chrome

- **Occurs on _both_ messenger.com and Facebook**

**Describe the problem**
When other people reply to messages in chat the bubble is shaded lighter than normal - not too sure whether it is a feature or a bug but it does hamper readability (and the general 'dark mode' vibe).

Not too sure what the corresponding code is that is related to these issues.

**Screenshots:**
![image](https://user-images.githubusercontent.com/62192447/80218530-a3322900-8684-11ea-9932-95888b642902.png)
[Not hovered on]

![image](https://user-images.githubusercontent.com/62192447/80218557-b04f1800-8684-11ea-97ab-bd866fa94cad.png)
[Hovered on]

P.S when clicking replies it takes you to the original message, the button to take you back to the bottom of the chat is also has shading issues.

Also not sure what the corresponding code is.

**Screenshot:**
![image](https://user-images.githubusercontent.com/62192447/80218720-e12f4d00-8684-11ea-9571-0770fb1037af.png)
[Whether hovered on or not it remains static]

**Comment by indigo5ive** [comment]
What I've taken notice is that it appeared recently (a message around 10PM had this issue).
Replies before that time worked fine 🤔

**Comment by cicerakes** [comment]
I assumed this might've been due to an update I hadn't received yet, but I'm still unable to reproduce both issues.

**Comment by cicerakes** [comment]
This issue won't occur on the latest version of Messenger.
