### ISSUE TITLE
white search field and dark icons on dark background

### ISSUE THREAD

**Issue by joshsleeper** [cicerakes/DarkNight-FBMessenger#2]
- **Browser:** Firefox 68.0.1 64-bit
- **Occurs on messenger.com or Facebook?** messenger.com

**Describe the problem**

1. Search field is white instead of the dark grey it used to be
1. Some icons (Choose a sticker, Play a game) are dark on the dark background

**Screenshots:**

##### white search field

![image](https://user-images.githubusercontent.com/849941/61747175-4c04ce00-ad6b-11e9-8a90-84a8d56339e0.png)

##### dark icons on dark background

![image](https://user-images.githubusercontent.com/849941/61747309-9423f080-ad6b-11e9-9295-7c579e4d4faa.png)

**Comment by cicerakes** [comment]
Re-installing [v1.0.1](https://raw.githubusercontent.com/cicerakes/DarkNight-FBMessenger/44fbbbbcc636f476c35a4d02e17383d642fd9337/DarkNightFBM.user.css) should fix this. 

It seems that the updates I made in v1.0.2 are for a newer version of messenger that hasn't rolled out to everyone yet.

**Comment by joshsleeper** [comment]
Dang slow rollouts 😑 

Thanks for the workaround for the time being~
