### ISSUE TITLE
White bar at bottom of page at certain page zoom level

### ISSUE THREAD

**Issue by indigo5ive** [cicerakes/DarkNight-FBMessenger#20]
- **Browser:** Chrome
- **Occurs on messenger.com or Facebook?** messenger.com

**Describe the problem**
When page is at 90% zoom, there is a white bar below the messge text box.
This only occurs when page is on 90% zoom.

**Screenshots:**
![image](https://user-images.githubusercontent.com/62192447/92441514-b425a600-f1f1-11ea-9b81-d809c503f03a.png)
![image](https://user-images.githubusercontent.com/62192447/92441531-bab41d80-f1f1-11ea-994c-14922d39f81a.png)

**Comment by cicerakes** [comment]
I can't reproduce this on my end (at all zoom levels), so I won't be able to fix it for now.

**Comment by mxdanger** [comment]
I was unable to reproduce this either. Unless @indigo5ive can reproduce this issue again, this should be closed.

**Comment by TheMadRuffian** [comment]
I am not able to reproduce it either.

**Comment by cicerakes** [comment]
Closed until someone can reproduce it.
