### ISSUE TITLE
No dark theme applied

### ISSUE THREAD

**Issue by NellyWhads** [cicerakes/DarkNight-FBMessenger#21]
- **Browser:** Chrome: 86.0.4240.198 (Official Build) (64-bit)
- **Occurs on messenger.com or Facebook?** Both

**Describe the problem**
A clear and concise description of what the bug is and/or provide steps to reproduce the issue.

Style loaded using Stylus - no theme is applied. I image the div tags have all changed.

**Screenshots:**
Add screenshots to help explain your problem.
[Insert regularly white-themed messenger image here]

**Comment by lplit** [comment]
Same issue here, was working fine for the longest time, stopped working yesterday. 

Seems like messenger behaves a bit differently though, so I'm assuming it's because of changes of FB's end.
