### ISSUE TITLE
Chat with multiple users - user list names are black

### ISSUE THREAD

**Issue by Alxandr** [cicerakes/DarkNight-FBMessenger#22]
- **Browser:** Chrome Version 86.0.4240.198 (Official Build) (64-bit)
- **Occurs on messenger.com or Facebook?** messenger.com

**Describe the problem**
The users list in a multi-user chat has wrong colors on the names - making them a bit inneligable.

**Screenshots:**
![image](https://user-images.githubusercontent.com/112334/99889620-3a7d5000-2c57-11eb-8440-5ad82022b30f.png)

**Comment by cicerakes** [comment]
This seems to be an issue occurring on the previous version of Messenger (which I couldn't reproduce), so I won't be fixing it since the next update should resolve it.
