### ISSUE TITLE
new messenger site is not working

### ISSUE THREAD

**Issue by kinglau66** [cicerakes/DarkNight-FBMessenger#23]
- **Firefox 83.0 :** 
- **Occurs on messenger.com** 

**Describe the problem**
messenger.com is updated. The UI feels different and dark mode is not working anymore.
Think they aligned messenger.com with the facebook counterpart.

**Screenshots:**
pretty white
![image](https://user-images.githubusercontent.com/15945904/101251699-e8f5ba80-3758-11eb-807b-dde45c382d49.png)

**Comment by kinglau66** [comment]
its working now. don't know what's the previous issue

**Comment by kinglau66** [comment]
its not working again. same details as previous

**Comment by teranex** [comment]
Thanks for the fix, my eyes are happy again :+1:

**Comment by joshsleeper** [comment]
not sure what the correct way to handle this is, but I'm still seeing the old UI (which is now blinding white, for obvious reasons) on Firefox 84.
I wonder if it has anything to do with whether you have a "real" Facebook account or not?
for example, I only have my phone number registered to log in to fb messenger, but haven't had a full Facebook account for years.

is there any way to include both the new and old CSS for a while to cover both versions of the site, or would they conflict?

**Comment by cicerakes** [comment]
@joshsleeper Two options: 
**If you want to keep just one (and have auto updates disabled):**
1. You can rollback to the [previous version here](https://github.com/cicerakes/DarkNight-FBMessenger/raw/b2c40bcfbc42d5704c11844f4dccd466254171aa/DarkNightFBM.user.css).
2. Wait until your Messenger updates before manually updating it to the latest version.

**If you want to have both (and keep your auto updates enabled for other themes):** 
1. Uninstall your current version.
2. Install [the previous version](https://github.com/cicerakes/DarkNight-FBMessenger/raw/b2c40bcfbc42d5704c11844f4dccd466254171aa/DarkNightFBM.user.css) and disable updates (it should be an option when installing).
3. Open the theme and rename it to anything else (e.g. add "old" to the name). Make sure to save your changes. 
4. Install [the current version](https://raw.githubusercontent.com/cicerakes/DarkNight-FBMessenger/master/DarkNightFBM.user.css).
5. When you don't need the old one anymore, just delete it.

**Comment by joshsleeper** [comment]
huh, I'd never even thought of modifying the old version and installing both, clever!
thanks a bundle, that works like a charm for me, and thanks for all the hard work you do maintaining this theme!
