### ISSUE TITLE
[maybe feature request?] support for custom colored chats

### ISSUE THREAD

**Issue by joshsleeper** [cicerakes/DarkNight-FBMessenger#6]
- **Browser:** Firefox 68.0.1 64-bit on Windows 10 Pro
- **Occurs on messenger.com or Facebook?** messenger.com

**Describe the problem**
Despite setting a custom color for a chat, message bubbles all appear as the same default blue.

**Screenshots:**

#### green chat color with dark style enabled

![image](https://user-images.githubusercontent.com/849941/62561022-27acf500-b833-11e9-8a17-f882d9ea8363.png)

#### green chat color with dark style disabled

![image](https://user-images.githubusercontent.com/849941/62560990-0d731700-b833-11e9-932e-4c656c8c89e7.png)

**Comment by cicerakes** [comment]
This is fixed in the next update. 

If you're still using v1.0.1 and can't update, then changing the "Coloured Chat Bubbles" setting to "Enabled" instead of "Enabled - Darker Default Blue" should fix this in the meantime.

**Comment by joshsleeper** [comment]
Ahh nice, thanks!
FYI, I saw the style update for me just by checking for updates in Stylus, but it holds the same `1.0.3` release version, so unsure if that was intentional or not.

Either way, the new update does indeed show custom chat colors like expected, hurrah!

That said, I did notice that the `Enabled - Darker Default Blue` setting doesn't seem to be working now, although that could be another artifact of me not having the latest messenger.com code as with my other recent issue (#2)

**Comment by cicerakes** [comment]
> it holds the same `1.0.3` release version 

I haven't actually incremented the version number to 1.0.4 yet, since I wanted to double-check some things later.

> the `Enabled - Darker Default Blue` setting doesn't seem to be working 

Just as you suspected, it's due to you having the previous version of messenger.

**Comment by joshsleeper** [comment]
> I haven't actually incremented the version number to 1.0.4 yet, since I wanted to double-check some things later.

totally get it, was just saying that I received those changes as an update, but the version hadn't changed and I wasn't sure if I was _supposed_ to receive them without a version change.
I'm not a userstyle-guru, so I just wasn't sure if that was expected or not is all!

> Just as you suspected, it's due to you having the previous version of messenger.

facebook pls :cry:
